version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
    day: wednesday
    time: "11:00"
    timezone: Europe/London
  open-pull-requests-limit: 99
  allow:
  - dependency-type: indirect
