version: 1

update_configs:
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "weekly"
    allowed_updates:
      - match:
          dependency_type: "indirect" # only top level dependencies
          update_type: "all"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
